FROM python:3.10-slim

WORKDIR /app

COPY requirements_worker.txt .
RUN pip install --no-cache-dir -r requirements_worker.txt

COPY . .

RUN python -m nltk.downloader vader_lexicon

CMD ["python", "worker.py"]
